import imgui_test_engine as te

import dimaxer_ui as ui


def BoxSlice():
    ui.select_view_ribbon_tab()
    ui.item_click("view.camera.isometric_view", 0, 0)
    ui.select_post_ribbon_tab()
    ui.import_model_post("dmh1/19-0.000949999958.dmh.dat")
    ui.ribbon_hide_all_and_select_mesh()
    ui.item_click("post.top.slice_panel", 0, 8)
    ui.combo_click("post.slice.combo_type", "Box")
    ui.item_click("post.slice.show_preview")
    te.Sleep(1)
    ui.capture_renderview(8)
    ui.item_click("post.slice.roweditor_plus")
    ui.item_input_value("post.slice.roweditor_edit_r1", 0.25)
    ui.item_click("post.slice.roweditor_plus")
    ui.item_input_value("post.slice.roweditor_edit_r2", -0.25)
    ui.item_click("post.slice.roweditor_plus")
    ui.scroll_to_bottom("post.slice.roweditor_scroll_area")
    ui.item_input_value("post.slice.roweditor_edit_r3", 0.5)
    ui.item_click("post.slice.roweditor_minus")
    ui.item_click_apply("post.slice.apply")
    ui.wait_alias("post.ribbon.mesh_slice1", 30.0)
    ui.item_click("post.quickaccess.fit_data", 0, 8)
    te.Sleep(2)
    ui.capture_renderview(8)

    ui.item_double_click("post.ribbon.mesh_slice1")
    te.Sleep(1)
    ui.capture_window("post.slice.plugin_window", 8)
    ui.item_click("post.ribbon.vis_slice1")
    ui.item_click("post.ribbon.vis_vol19")
    ui.item_click("post.slice.show_preview")
    ui.item_click("post.slice.triangulate")
    ui.item_click("post.slice.roweditor_x")
    ui.item_click("post.slice.roweditor_plus")
    ui.item_input_value("post.slice.roweditor_edit_r0", 0)
    ui.item_input_value("post.slice.pos_0", -0.5)
    ui.item_input_value("post.slice.pos_1", -0.5)
    ui.item_input_value("post.slice.pos_2", -0.5)
    te.Sleep(1)
    ui.capture_renderview(8)
    ui.item_input_value("post.slice.rot_0", 30)
    ui.item_input_value("post.slice.rot_1", 30)
    ui.item_input_value("post.slice.rot_2", 30)
    te.Sleep(1)
    ui.capture_renderview(8)
    ui.item_input_value("post.slice.len_0", 1)
    ui.item_input_value("post.slice.len_1", 1)
    ui.item_input_value("post.slice.len_2", 1)
    te.Sleep(1)
    ui.capture_renderview(8)
    ui.item_click("post.ribbon.vis_vol19")
    ui.item_click("post.slice.ref_bounds")
    ui.item_input_value("post.slice.range_x0", -0.3)
    ui.item_input_value("post.slice.range_x1", 0.7)
    ui.item_input_value("post.slice.range_y0", -0.2)
    ui.item_input_value("post.slice.range_y1", 0.8)
    ui.item_input_value("post.slice.range_z0", -0.1)
    ui.item_input_value("post.slice.range_z1", 0.9)
    te.Sleep(1)
    ui.capture_renderview(8)
    ui.item_click_apply("post.slice.apply")
    ui.capture_renderview(8)

    ui.item_double_click("post.ribbon.mesh_slice1")
    te.Sleep(1)
    ui.capture_window("post.slice.plugin_window", 8)
    ui.item_click("post.slice.exit")


def CylinderSlice():
    ui.import_model_post("dmh1/19-0.000949999958.dmh.dat")
    ui.ribbon_hide_all_and_select_mesh()
    ui.item_click("post.top.slice_panel", 0, 8)
    ui.combo_click("post.slice.combo_type", "Cylinder")
    ui.item_click_apply("post.slice.apply")
    ui.capture_renderview(8)


def PlaneSlice():
    ui.import_model_post("dmh1/19-0.000949999958.dmh.dat")
    ui.ribbon_hide_all_and_select_mesh()
    ui.item_click("post.top.slice_panel", 0, 8)
    ui.item_click("post.slice.z_normal")
    ui.item_click_apply("post.slice.apply")
    ui.capture_renderview(8)


def SphereSlice():
    ui.import_model_post("dmh1/19-0.000949999958.dmh.dat")
    ui.ribbon_hide_all_and_select_mesh()
    ui.item_click("post.top.slice_panel", 0, 8)
    ui.combo_click("post.slice.combo_type", "Sphere")
    ui.item_click_apply("post.slice.apply")
    ui.capture_renderview(8)
